### ISSUE TITLE
Option to remove '@' sign

### ISSUE THREAD

**Issue by abelski21** [afconsult/quill-mention#9]
Is there a way I can remove the at '@' sign in the mention span once we select an item in from the dropdown?

**Comment by MadSpindel** [comment]
You can use CSS to hide it:

```css
.ql-mention-at-sign {
  display:none;
}
```
